services:
  # Конфігураційні сервери
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all"]
    ports:
      - "26050:27017"
    volumes:
      - configsvr1_data:/data/db

  configsvr2:
    image: mongo:latest
    container_name: configsvr2
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all"]
    ports:
      - "26051:27017"
    volumes:
      - configsvr2_data:/data/db

  configsvr3:
    image: mongo:latest
    container_name: configsvr3
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all"]
    ports:
      - "26052:27017"
    volumes:
      - configsvr3_data:/data/db

  # Шард 1
  shard1:
    image: mongo:latest
    container_name: shard1
    command: ["mongod", "--replSet", "shard1ReplSet", "--shardsvr", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - shard1_data:/data/db

  # Шард 2
  shard2:
    image: mongo:latest
    container_name: shard2
    command: ["mongod", "--replSet", "shard2ReplSet", "--shardsvr", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - shard2_data:/data/db

  # Шард 3
  shard3:
    image: mongo:latest
    container_name: shard3
    command: ["mongod", "--replSet", "shard3ReplSet", "--shardsvr", "--bind_ip_all"]
    ports:
      - "27020:27017"
    volumes:
      - shard3_data:/data/db

  # Mongos (Маршрутизатор)
  mongos:
    image: mongo:latest
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr1:27017,configsvr2:27017,configsvr3:27017", "--bind_ip_all"]
    ports:
      - "27017:27017"
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1
      - shard2
      - shard3

volumes:
  configsvr1_data:
  configsvr2_data:
  configsvr3_data:
  shard1_data:
  shard2_data:
  shard3_data:
